languageCode = 'en-us'
title = 'releasewerk'
enableGitInfo = false

[module]
[[module.imports]]
    path = "github.com/alex-shpak/hugo-book"
    disable = false

[params]
    BookTheme = "light"
    BookToC = true
    BookSection = "stats"
    BookSearch = false
    BookComments = false
     BookDateFormat = "2006-01-02"

[markup.tableOfContents]
    startLevel = 1

[security]
  enableInlineShortcodes = true
